# Generated by Django 2.2.5 on 2019-09-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredNo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
