# Generated by Django 2.2.5 on 2019-09-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredno',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
